language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
services:
  - postgresql
addons:
  postgresql: 9.3
before_script:
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
  - psql -c 'create database active_record_embedded_doc_test' -U postgres
script:
  - cd spec/dummy; RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
